export const plunkDevEnv = {
  NODE_ENV: 'development',
  JWT_SECRET: 'hBx9Xh8J6KOMAGAsSjvcZJBT5TWyIkFX',
  PORT: '8080',
  USE_HTTPS: 'false',
  API_URI: 'http://127.0.0.1:5173/mail-api',
  DASHBOARD_URI: 'http://127.0.0.1:5173/mail',
  LANDING_URI: 'http://localhost:4000',
  WIKI_URI: 'http://localhost:1000',
  REDIS_URL: 'redis://127.0.0.1:56379',
  DATABASE_URL: 'postgresql://postgres:postgres@localhost:55432/postgres',
  DIRECT_DATABASE_URL: 'postgresql://postgres:postgres@localhost:55432/postgres',
  S3_ENDPOINT: 'http://localhost:9000',
  S3_ACCESS_KEY_ID: 'plunk',
  S3_ACCESS_KEY_SECRET: 'plunkminiopass',
  S3_BUCKET: 'uploads',
  S3_PUBLIC_URL: 'http://localhost:9000/uploads',
  S3_FORCE_PATH_STYLE: 'true',
  AWS_SES_REGION: 'us-east-1',
  AWS_SES_ACCESS_KEY_ID: 'local-dev-placeholder',
  AWS_SES_SECRET_ACCESS_KEY: 'local-dev-placeholder',
  SES_CONFIGURATION_SET: 'plunk-configuration-set',
  SES_CONFIGURATION_SET_NO_TRACKING: 'plunk-configuration-set-no-tracking',
  AUTO_PROJECT_DISABLE: 'false',
  VERIFY_EMAIL_ON_SIGNUP: 'false',
};
