import {createMDX} from 'fumadocs-mdx/next';

// Note: openapi.local.json is generated by the prebuild/predev script
// See scripts/generate-openapi.js

const withMDX = createMDX();

/** @type {import('next').NextConfig} */
const config = {
  reactStrictMode: true,
  output: 'standalone', // Optimized for Docker
};

export default withMDX(config);
